### ISSUE TITLE
How to unlock automatically

### ISSUE THREAD

**Issue by hiruthicShaSS** [saksham-jain/Lock-Unlock-PC-Using-Face-Recognition#4]
Hey, I saw your [](https://github.com/saksham-jain/Lock-Unlock-Laptop-PC-Screen-Using-Face-Recognition/blob/master/lock_unlock_face_recognition.py) code and it seems like the code can lock but unlocking the system should be manually done, even if the owner is in front of the camera...Right!?.
So, I also did the same project in my system like 6 - 8 months ago and I still didn't figure out how to unlock the system like we lock the system using the command **LockWorkStation** from **user32.dll**...
If you find how to do that just ping me: _@hiruthic2002_

**Comment by saksham-jain** [comment]
For unlocking i propose to disable your windows lock and when you open your laptop python script will run automatically and it restricts acess to the laptop until owner comes in front of the camera.
